In [5]:
import pandas as pd
import json
import numpy as np
import os
import warnings
warnings.filterwarnings('ignore')

voting_data = pd.read_csv("https://www.electoralcommission.org.uk/__data/assets/file/0014/212135/EU-referendum-result-data.csv")
county_vote_df = voting_data[['Region','Area', 'Valid_Votes', 'Remain', 'Leave']]
county_vote_df.name = 'county_vote_df'
region_vote_df = voting_data[['Region', 'Valid_Votes', 'Remain', 'Leave']].groupby('Region').agg(np.sum)
region_vote_df.name = 'region_vote_df'

dataframes = [county_vote_df, region_vote_df]
for dataframe in dataframes:
    dataframe.loc[:,'Pct_Remain'] = dataframe['Remain']/dataframe['Valid_Votes']
    dataframe.loc[:,'Pct_Leave'] = dataframe['Leave']/dataframe['Valid_Votes']
     
    output_file = os.path.join('..', 'Resources', dataframe.name +'.csv')
    #  Open the output file
    with open(output_file, 'w') as datafile:
        dataframe.to_csv(output_file)

In [6]:
region_vote_df

                          Valid_Votes   Remain    Leave  Pct_Remain  Pct_Leave
Region
East                          3328983  1448616  1880367    0.435153   0.564847
East Midlands                 2508515  1033036  1475479    0.411812   0.588188
London                        3776751  2263519  1513232    0.599330   0.400670
North East                    1340698   562595   778103    0.419628   0.580372
North West                    3665945  1699020  1966925    0.463460   0.536540
Northern Ireland               790149   440707   349442    0.557752   0.442248
Scotland                      2679513  1661191  1018322    0.619960   0.380040
South East                    4959683  2391718  2567965    0.482232   0.517768
South West                    3172730  1503019  1669711    0.473731   0.526269
Wales                         1626919   772347   854572    0.474730   0.525270
West Midlands                 2962862  1207175  1755687    0.407435   0.592565
Yorkshire and The Humber      2739235  1158298  1580937    0.422855   0.577145